language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

env:
  - GO111MODULE=on

install:
  - go get -d -t ./...
  - go get -u golang.org/x/lint/golint

script:
  - golint -set_exit_status ./...
  - go vet ./...
  - go test ./...
