---
name: static check
on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
